Migrated to asynchronous programming. Converted ImageGen to context m…
acheong08/EdgeGPT pull request #232
Opened 2023-03-28 19:20 UTC by scmanjarrez

…anager. Added quiet flag to be used as module without cluttering"

2023-03-29 00:04 UTC, acheong08 requested changes
Needs to be different class. We want both a sync and async version. The async version can extend the sync

2023-03-29 14:42 UTC, scmanjarrez commented
Okay, I have reverted ImagenGen changes and added async to a new class called ImageGenAsync, is that good?

2023-04-01 10:28 UTC, acheong08 requested changes

2023-04-01 10:28 UTC, acheong08 commented on src/ImageGen.py
> +        asyncio.run(async_image_gen(args))
The default should be sync

2023-04-01 10:29 UTC, acheong08 commented
Sorry for the slow response. My email got very cluttered

2023-04-01 10:29 UTC, scmanjarrez commented
I'm currently working with the update, sorry.

2023-04-01 11:01 UTC, acheong08 approved these changes

2023-04-01 11:06 UTC, merged