Support change locale,fix some precise mode in Chinese's issue.
acheong08/EdgeGPT pull request #460
Opened 2023-06-01 05:43 UTC by VMTask

2023-06-01 08:29 UTC, acheong08 requested changes

2023-06-01 08:29 UTC, acheong08 commented on docs/README.md
> +  <a href="https://githubfast.com/acheong08/EdgeGPT">
Suspicious link?

2023-06-01 08:29 UTC, acheong08 commented on docs/README.md
> + <a href="https://githubfast.com/acheong08/EdgeGPT/graphs/contributors">
same here

2023-06-01 08:29 UTC, acheong08 commented on src/EdgeGPT.py
> +                        ],
Perhaps allow customization with a few defaults via a map.

2023-06-01 08:29 UTC, acheong08 commented on src/EdgeGPT.py
> +        locale: bool = False,
bool?

2023-06-01 08:29 UTC, acheong08 commented on src/EdgeGPT.py
> +                        "market": "en-US",
Perhaps this should reflect locale?

2023-06-01 08:59 UTC, acheong08 approved these changes

2023-06-01 09:00 UTC, merged

2023-06-04 10:31 UTC, d1h1r1 commented
您好，是需要自己改EdgeGPT.py吗，我更新到0.8.0版本了，回答的和网页上还是不一样，网页上可以搜出来，EdgeGPT搜不出来

2023-06-04 12:27 UTC, VMTask commented on src/EdgeGPT.py
> +        locale: bool = False,
Yes,it's my fault.

2023-06-04 12:29 UTC, VMTask commented on docs/README.md
> +  <a href="https://githubfast.com/acheong08/EdgeGPT">
I

> 您好，是需要自己改EdgeGPT.py吗，我更新到0.8.0版本了，回答的和网页上还是不一样，网页上可以搜出来，EdgeGPT搜不出来

在原有的启动命令后加 `--locale zh-CN`就能搜到了

2023-06-04 12:29 UTC, VMTask commented
> 您好，是需要自己改EdgeGPT.py吗，我更新到0.8.0版本了，回答的和网页上还是不一样，网页上可以搜出来，EdgeGPT搜不出来

在原有的启动命令后加 --locale zh-CN就能搜到了

2023-06-04 12:38 UTC, d1h1r1 commented
我是用python    
async def main(txt):
        cookies = json.loads(open("../cookies.json", encoding="utf-8").read())
        bot = await Chatbot.create(cookies=cookies)
        ans = await bot.ask(prompt=txt, conversation_style=ConversationStyle.creative)
        ans = ans['item']['messages'][-1]['adaptiveCards'][0]['body'][0]['text']
        print(txt + "\n" + ans)
        await bot.close()
        return ans

    asyncio.run(main(txt))
控制的哦

2023-06-05 06:23 UTC, xhzth70911 commented
> > 您好，是需要自己改EdgeGPT.py吗，我更新到0.8.0版本了，回答的和网页上还是不一样，网页上可以搜出来，EdgeGPT搜不出来
> 
> 在原有的启动命令后添加--locale zh-CN就可以搜索到了

>python -m EdgeGPT --cookie-file D:\EdgeGPT-0.8.1\src\cookie.txt --locale zh-CN
0.8.1的版本，报错EdgeGPT.py: error: unrecognized arguments: --locale zh-CN，没有这个参数啊

2023-06-07 08:12 UTC, d1h1r1 commented
> > 您好，是需要自己改 EdgeGPT.py 吗，我更新到0.8.0版本了，回答的和网页上还是不一样，网页上可以搜出来，EdgeGPT搜不出来
> 
> 在原有的启动命令后加 --locale zh-CN就能搜到了

谢谢这个问题我解决了，现在这个项目可以实现联系上下文吗

2023-06-08 14:06 UTC, RockChinQ commented
> > > 您好，是需要自己改 EdgeGPT.py 吗，我更新到0.8.0版本了，回答的和网页上还是不一样，网页上可以搜出来，EdgeGPT搜不出来
> > 
> > 
> > 在原有的启动命令后加 --locale zh-CN就能搜到了
> 
> 谢谢这个问题我解决了，现在这个项目可以实现联系上下文吗

可以的