Improvements to Query, ImageQuery and Cookie helper classes
acheong08/EdgeGPT pull request #507
Opened 2023-06-06 18:15 UTC by PFython

These are all imported from BingChatUtils.py

I've added that to py_modules in setup.py - please revert or amend as necessary so that people can simple access as per the updated README file i.e. `from BingChatUtils import Query`

2023-06-06 20:31 UTC, MonsterDruide1 requested changes

2023-06-06 20:31 UTC, MonsterDruide1 commented on src/BingChatUtils
Should have a `.py` extension

2023-06-06 22:20 UTC, PFython commented on src/BingChatUtils
Sorry - that'll teach me for manually renaming in Github in a hurry.  Fixed.

2023-06-07 02:38 UTC, acheong08 commented
> BingChatUtils

I would prefer it to remain `EdgeUtils`

2023-06-08 23:01 UTC, PFython commented
No problem - done.

2023-06-09 09:40 UTC, acheong08 commented
Conflicts

2023-06-12 12:52 UTC, acheong08 commented
Should I resolve these conflicts manually and merge? Is it still a draft? 

CC: @JimouChen @StolenGalaxy @starhui70520

2023-07-07 13:06 UTC, closed without merging

2023-07-07 14:59 UTC, acheong08 commented
I resolved and merged in 5756789c1d5c0e1562f216d590945b89fc19a2c2