Added function to delete chat on the server. Updated spanish localiza…
acheong08/EdgeGPT pull request #541
Opened 2023-06-13 21:47 UTC by scmanjarrez

…tion. Closes #540

2023-06-13 21:49 UTC, scmanjarrez commented
Related #540

2023-06-14 09:31 UTC, acheong08 requested changes

2023-06-14 09:31 UTC, acheong08 commented on src/EdgeGPT/chathub.py
> +    async def remove_and_close(self) -> None:
Would prefer to have this as `remove_conversation(conversation_id:str=None, conversation_signature:str=None,client_id:str=None)`

2023-06-14 09:31 UTC, acheong08 commented on src/EdgeGPT/chathub.py
> +        client_id = self.request.client_id
`conversation_id = conversation_id or self.request.conversation_id`

2023-06-14 09:31 UTC, acheong08 commented
Same for the Chatbot class

2023-06-14 09:32 UTC, acheong08 commented on src/EdgeGPT/chathub.py
> +        await self.session.aclose()
And this removed. Should be separate from close

2023-06-15 07:57 UTC, merged

2023-06-15 07:59 UTC, scmanjarrez commented
Sorry, I've been pretty busy. Couldn't do the suggested changes

2023-06-15 08:01 UTC, acheong08 commented
No worries. I resolved them in https://github.com/acheong08/EdgeGPT/commit/b08633010b2b0db3ae58a1fcc098f7846906f5eb